[build]
builder = "nixpacks"

[build.nixpacksConfig]
cmds = ["npm run db:generate"]

[deploy]
startCommand = "npm start"

[deploy.env]
PRISMA_CLI_BINARY_TARGETS = "debian-openssl-1.1.x"
PRISMA_QUERY_ENGINE_BINARY = "debian-openssl-1.1.x" 