[build]
builder = "nixpacks"

[build.nixpacksConfig]
cmds = ["npm ci", "npm run db:generate"]

[deploy]
startCommand = "node src/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"
PRISMA_CLI_BINARY_TARGETS = "debian-openssl-1.1.x"
PRISMA_QUERY_ENGINE_BINARY = "debian-openssl-1.1.x" 